#! /bin/bash

max=0
test_nb=100
value_nb=500
min_val=1
moyen=0;
max_val=5000
for i in `seq 1 $test_nb`
do
    arg=`shuf -i $min_val-$max_val -n $value_nb`
    arg=`echo $arg | sed 's/\n/ /g'`
    current=`./push_swap $arg | wc -l`
    if [ $current -gt $max ]
    then
        max="$current"
        worst="$arg"
    fi
    moyen=$(( $moyen + $current ))
done
echo $((moyen / test_nb))
echo "for $test_nb different tests with $value_nb different random values between $min_val and $max_val:\nmax count of instructions is $max\nit was reached with this list : \n$worst"
echo "for $test_nb different tests with $value_nb different random values between $min_val and $max_val:\nmax count of instructions is $max\nit was reached with this list : $worst\n" >> historique
echo "for $test_nb different tests with $value_nb different random values between $min_val and $max_val:\nmax count of instructions is $max\nit was reached with this list : $worst\n" > last
echo $((moyen / test_nb)) >> historique
echo $((moyen / test_nb)) >> last

